/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_pace_PaceJni */

#ifndef _Included_edu_pace_PaceJni
#define _Included_edu_pace_PaceJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_pace_PaceJni
 * Method:    initializeJni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_pace_PaceJni_initializeJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
